### ISSUE TITLE
Error unpacking rpm package httpd-*

### ISSUE THREAD

**Issue by duketwo** [UniconLabs/dockerized-idp-testbed#12]
While using a Ubuntu/Debian host you might encounter the error above.

The solution: https://github.com/docker/hub-feedback/issues/725
`service docker stop
`
`dockerd --storage-driver=devicemapper &
`
`docker-compose up`

**Comment by jtgasper3** [comment]
Hi @duketwo,

While not really a problem with the testbed itself, but Docker on Ubuntu/Debian, this is a great note for others that may run into this. 

Thanks for sharing.
