### ISSUE TITLE
How to log out?

### ISSUE THREAD

**Issue by fisx** [UniconLabs/dockerized-idp-testbed#16]
Is there an easier way to logout than destroying the browser state?

Great piece of code, thanks!

**Comment by jtgasper3** [comment]
Not at this point. Having multiple IdPs with multi client applications makes it hard. SLO is probably do able but I've not had a reason to implement that. This project is mostly there to confirm that my Docker images work as expected.

I generally have an Incognito or Private Browser session going that I  can quickly close and re-open.

**Comment by fisx** [comment]
that helps, thanks again!  good to know i haven't missed anything obvious.  (-:
