### ISSUE TITLE
Can't contact LDAP server

### ISSUE THREAD

**Issue by errst** [UniconLabs/dockerized-idp-testbed#17]
After following instructions i've got this output:
https://gist.github.com/errst/43bbb3179ed29d00e30c88d9deb71e53

Specific detail:
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
ERROR: Service 'ldap' failed to build: The command '/bin/sh -c useradd ldapadmin     && rm -fr /var/lock /usr/lib/systemd/system     && sed -i 's/checkHostname {/checkHostname {\nreturn();/g' /usr/lib64/dirsrv/perl/DSUtil.pm     && sed -i 's/updateSelinuxPolicy($inf);//g' /usr/lib64/dirsrv/perl/*     && sed -i '/if (@errs = startServer($inf))/,/}/d' /usr/lib64/dirsrv/perl/*     && setup-ds.pl --silent --file /ds-setup.inf     && /usr/sbin/ns-slapd -D /etc/dirsrv/slapd-dir     && sleep 3     && ldapadd -H ldap:/// -f /users.ldif -x -D "cn=Directory Manager" -w password' returned a non-zero code: 255

How can i achieve this issue? Thanks.

**Comment by jtgasper3** [comment]
Something changed with 389-ds and it takes longer than 3 seconds to start now. I've updated the code in other places to be more dynamic but missed this reference.

**Comment by jtgasper3** [comment]
This should be fixed now. I did a direct update, so I might have missed something. Please pull again and restart it. Then let me know how it goes. IF something does break, the last screen or two of logging should be sufficient. Thanks.

**Comment by errst** [comment]
@jtgasper3 awesome, it worked. thanks.
