### ISSUE TITLE
failure of shibd-redhat to run

### ISSUE THREAD

**Issue by fighne** [UniconLabs/dockerized-idp-testbed#26]
dockerized-idp-testbed peterfeeney$ docker-compose up
Creating network "dockerized-idp-testbed_front" with driver "bridge"
Creating network "dockerized-idp-testbed_back" with driver "bridge"
Creating dockerized-idp-testbed_sp_1          ... done
Creating dockerized-idp-testbed_httpd-proxy_1 ... done
Creating dockerized-idp-testbed_ldap_1        ... done
Creating dockerized-idp-testbed_idp_1           ... done
Creating dockerized-idp-testbed_simplesamlphp_1 ... done
Creating dockerized-idp-testbed_php-cas_1       ... done
Attaching to dockerized-idp-testbed_sp_1, dockerized-idp-testbed_ldap_1, dockerized-idp-testbed_httpd-proxy_1, dockerized-idp-testbed_idp_1, dockerized-idp-testbed_simplesamlphp_1, dockerized-idp-testbed_php-cas_1
sp_1             | /usr/local/bin/httpd-shibd-foreground: line 7: /etc/shibboleth/shibd-redhat: Permission denied
sp_1             | httpd-error [Thu May 23 11:15:22.795194 2019] [suexec:notice] [pid 1:tid AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)

this is due to the file having no execute properties set

SP docker file needs to be

FROM unicon/shibboleth-sp

RUN yum -y update \
    && yum -y install php mod_ssl   

COPY etc-shibboleth /etc/shibboleth/
RUN chmod 755 /etc/shibboleth/shibd-redhat
COPY etc-httpd/ /etc/httpd/
COPY var-www-html/ /var/www/html/

fix works on docker for Mac and docker for windows

**Comment by jtgasper3** [comment]
Thanks for the report. It looks like something changed with the installation process as the standalone unicon/shibboleth-sp image appears to require a similar change.

**Comment by fighne** [comment]
I know this is off theme
I'm having major problems trying to setup the discovery service with this. I've added the following to the sp Dockerfile
RUN yum install -y shibboleth-embedded-ds
Followed the instructions here
https://wiki.shibboleth.net/confluence/display/EDS10/
Made changes in the proxypass so added the shibboleth-ds
But I get a "The requested URL /shibboleth-ds/ was not found on this server." error! Any hints or ideas welcome

**Comment by jtgasper3** [comment]
I'd probably attach to the running SP container and curl/wget it and see if it is available there, then you'll know where to focus.

**Comment by fighne** [comment]
thanks for that, the proxy was working it's the SP complaining of the following "Failed to download metadata from /Shibboleth.sso/DiscoFeed" Looks as thou if the whole process was setup for example.org it might be easier to transfer to a live site? What's your opinion?

**Comment by jtgasper3** [comment]
Sorry, was out of the office last week and just now catching up on emails. 

The Discovery Service requires configuration: https://wiki.shibboleth.net/confluence/display/EDS10/3.+Configuration. You'll need to use Docker/Kubernetes Configs/ConfigMaps to link in your configuration.

**Comment by jtgasper3** [comment]
I think the core issue was fixed with a change to the Shib SP image.
