### ISSUE TITLE
Seeing a lot of mirror timeouts....

### ISSUE THREAD

**Issue by hughbarronjohnson** [UniconLabs/dockerized-idp-testbed#28]
Trying to run docker-compose build and getting a lot of:

`http://download.opensuse.org/repositories/security%3A/shibboleth/CentOS_7/x86_64/libxmltooling8-3.0.4-3.2.x86_64.rpm: [Errno 12] Timeout on http://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/x86_64/libxmltooling8-3.0.4-3.2.x86_64.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
`

**Comment by jtgasper3** [comment]
The opensuse repos are problematic, but that is where the Shib project hosts its libraries, etc. It usually fixes after a day or so. Hopefully it started working fine for you.
