### ISSUE TITLE
Service Unavailable after docker-compose stop then start

### ISSUE THREAD

**Issue by carlosjm0325** [UniconLabs/dockerized-idp-testbed#29]
Although i'm unfortunately getting the same shibd listener exception others are getting. My issue has more to do with the fact that when I start up using docker compose, then stop, then try and restart (regardless of making changes or not) i unfortunately get "service unavailable" for the php-cas example.

All containers running, shibd process isn't even available on idp, proxy container is routing correctly because it works on first compose up...

Thoughts?

**Comment by carlosjm0325** [comment]
Was able to work around the issue by stopping, then running "system prune" - regular docker-compose up brought back up without issue

**Comment by TeamDman** [comment]
For others who find this, 
the fix was likely the update from jtgasper3 [here](https://github.com/UniconLabs/dockerized-idp-testbed/issues/27#issuecomment-507800404)
