### ISSUE TITLE
Instructions on how to integrate with external IDPs

### ISSUE THREAD

**Issue by dima767** [UniconLabs/dockerized-idp-testbed#4]
It would be super useful to have instructions on what needs to be done in SP image to integrate with external IDPs instead of using the internal one (in the docker container). And perhaps a separate branch with this SP integrated with testshib.org IDP, etc.

**Comment by jtgasper3** [comment]
That's not really the point of this project, but feel free to tackle it.

**Comment by dima767** [comment]
I'll do that locally and will put it in the separate repo.

**Comment by sahagin-dazs** [comment]
@dima767 did you ever do this? Was it as simple as swapping out the `sp/etc/shibboleth/idp-metadata.xml` file for a remote IdP and pointing the IdP to the SP instance?
