### ISSUE TITLE
DNS lookup failure for: sp ?

### ISSUE THREAD

**Issue by tomzeller** [UniconLabs/dockerized-idp-testbed#5]
Is a DNS entry for 'sp' necessary ?

After running 'docker-compose up', browsing to https://idptestbed/ and clicking on the link, I see : 

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /php-shib-protected/.
Reason: DNS lookup failure for: sp

**Comment by jtgasper3** [comment]
Hi @tomzeller,

That not good...
- What version of the Docker Engine are you running?
- What code branch are you running?
- Is there anything in the log that shows issues with the SP container starting up?
- Can you send me the output of `docker ps`?

Thanks.

**Comment by jtgasper3** [comment]
@tomzeller,

Just realized I missed your initial question. No, you do not need a DNS entry for "sp". Docker should added it to the container's `/etc/hosts` file or uses its own internal DNS server to provide the container ip to the dependent container... So it depends upon which version of the Docker Engine you are running.
